version: "2.24.5"
services:
  next-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    image: next-client-dev-v1

  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./server:/server
    image: node-server-dev-v1


