version: "2.24.5"
services:
  next-client:
    image: next-client-v1
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - AWS_ML_SERVER_API=http://localhost:8080
    restart: always
  
  node-server:
    image: node-server-v1
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always


