version: "3.8"
services:
  next-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
    image: next-client-dev-v1
    restart: unless-stopped

  node-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./server:/server
    image: node-server-dev-v1
    restart: unless-stopped


